mk:
    export JAVA_HOME=$(/usr/libexec/java_home -v 17)
    mvn -q -DskipTests package
    eval $(minikube -p minikube docker-env)
    docker image rm kafka-streams-fhri:latest -f
    eval $(minikube -p minikube docker-env)
    docker build -t kafka-streams-fhri:latest .
    kubectl delete deployment kafka-streams-fhri -n kafka --ignore-not-found=true
    kubectl apply -f ../configs/streams/kafka-streams-fhri.yaml
