apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: influx-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.lenses.streamreactor.connect.influx.InfluxSinkConnector
  tasksMax: 1
  config:
    # Key converter
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    
    value.converter: org.apache.kafka.connect.json.SchemalessJsonConverter
    value.converter.schemas.enable: false
    # value.converter.schema.registry.url: "https://raw.githubusercontent.com/stahlco/fhir_schema/refs/heads/main/fhir.schema.json"

    # InfluxDB connection
    topics: "wearables-fhri"
    connect.influx.url: "http://influx-service.kafka.svc.cluster.local:8086"
    connect.influx.db: "test"
    connect.influx.username: "test"
    connect.influx.password: "test"

    # Simplified KCQL - use the topic name as measurement initially -> Need to be updated
    connect.influx.kcql: "INSERT INTO test SELECT * FROM wearables-fhri WITHTIMESTAMP sys_time() STOREAS JSON"
    # Error handling
    errors.tolerance: all
    errors.log.enable: true
    errors.log.include.messages: true
    errors.deadletterqueue.topic.name: "influx-sink-dlq"
    errors.deadletterqueue.topic.replication.factor: 1
