apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: influx-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.lenses.streamreactor.connect.influx.InfluxSinkConnector
  tasksMax: 1
  config:
 
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false

    # Value is base64-encoded, but let's try with schemas first
    value.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter.schemas.enable: false

    # InfluxDB connection
    topics: "wearables-fhri"
    connect.influx.url: "http://influx-service.kafka.svc.cluster.local:8086"
    connect.influx.db: "test"
    connect.influx.username: "test"
    connect.influx.password: "test"
    connect.influx.kcql: "INSERT INTO wearables SELECT resourceType, id, status, effectiveDateTime, valueInteger FROM wearables-fhri WITHTIMESTAMP timestamp"
    
    # Error handling for debugging
    errors.tolerance: all
    errors.log.enable: true
    errors.log.include.messages: true
